### ISSUE TITLE
결제시 마일리지와 배송비 적용 안되는 문제

### ISSUE THREAD

**Issue by treasurej** [qw5414/nurigo#3]
결제시 마일리지와 배송비 적용 안되는 문제

결제화면에서 마일리지와 배송비를 적용했는데
결제하기하면 이니시스 화면에서 마일리지와 배송비가 적용되지 않은 가격으로 나오는 문제

https://www.cameron.co.kr:47741/nstore_tip/65685

정확한 해결방법인지는 모르지만 이렇게 하니까 적용은 됨.
정확한 원인이 무엇인지 확인해 봐야 함.

**Comment by qw5414** [comment]
fixed in https://github.com/qw5414/nurigo/commit/a650fbfa6fe8bb065984d17380ffc66a507636bf
