### ISSUE TITLE
상품별 CSV 다운로드 | 주문별 CSV 다운로드 "잘못된 요청입니다." 오류 해결

### ISSUE THREAD

**Issue by treasurej** [qw5414/nurigo#5]
상품별 CSV 다운로드 | 주문별 CSV 다운로드 "잘못된 요청입니다." 오류 해결

https://www.cameron.co.kr:47741/nstore_tip/82033

**Comment by qw5414** [comment]
fixed in https://github.com/qw5414/nurigo/commit/ebd19a78ca137a9ae2baeee399cc0f50ae02f8af
